### ISSUE TITLE
Update to webOSTV.js v1.2.3

### ISSUE THREAD

**Issue by bfanger** [procot/webostv#14]
**webOSTV.js v1.2.3**. 
* fixed the bug on keyboard.isShowing() method.

http://webostv.developer.lge.com/api/webostvjs/

**Comment by rbndelrio** [comment]
@bfanger you can use my fork for now:
```json
"dependencies": {
    "@procot/webostv": "https://github.com/rbndelrio/webostv.git"
}
```

**Comment by EdwinMeijne** [comment]
Hey, thanks!

**Comment by procot** [comment]
@bfanger @rbndelrio @EdwinMeijne 
Hi, the 1.2.3 version is released.
https://www.npmjs.com/package/@procot/webostv/v/1.2.3
