### ISSUE TITLE
Bump library version to 1.2.4

### ISSUE THREAD

**Issue by koenoe** [procot/webostv#21]
There's also a few new properties on DeviceInfo like hdr10, dolbyVision and dolbyAtmos

**Comment by hcodes** [comment]
https://github.com/procot/webostv/pull/22

**Comment by procot** [comment]
@koenoe 
Hi, the 1.2.4 version is released.
https://www.npmjs.com/package/@procot/webostv/v/1.2.4

**Comment by procot** [comment]
@koenoe 
Sorry, I didn't see a mistake in the source code of webOSTV.js in #22.
Fix a mistake in `@procot/webostv@1.2.5`
